baseURL = 'http://example.org/'
languageCode = 'en'
title = 'Yens - constructing...'
theme = "hugo-theme-monochrome"
defaultContentLanguage = "en"

[build]
  writeStats = true

[taxonomies]
category = "categories"
tag = "tags"
#series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
