navbarTitle = 'Yens Loff'
footer = "Copyright © 2021 by Yens"

enableZoomingJS = true
enableTOC = true
enableSiteSearch = true
enableMathJax = false

# Codeblock
usePrismJS = false
enablePrismJSLineNo = true
enableCodeCopy = true

# SEO
enableOpenGraph = true
enableTwitterCards = true
author = "yens.loff@gmail.com"

# Collapsible Menu
enableCollapsibleTOC = false
enableCollapsibleChangelogs = true
