baseURL = 'https://yensloff.com/'
languageCode = 'en-us'
title = 'Yens Loff'

theme = 'simplemod'

[markup]
    [markup.highlight]
        codeFences = true    
        lineNos = true       
        style = "github"
    [markup.goldmark]
        [markup.goldmark.extensions]
            typographer = true  
            table = true
        [markup.goldmark.renderer]
            unsafe = true
