name = 'Simplemod'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Simple portfolio and blog theme'

# The home page of the theme, where the source can be found
# homepage = 'https://github.com/owner/repo'

# If you have a running demo of the theme
# demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['blog', 'personal', 'minimal']
features = ['news', 'cyber security']

# If the theme has multiple authors
# authors = [
#   {name = 'Author', homepage = 'Your Site'},
#   {name = 'Author', homepage = 'Your Site'}
# ]

# If the theme has a single author
[author]
  name = 'Yens Loff'
  homepage = 'yensloff.com'

# If porting an existing theme
# [original]
#   author = 'Name of original author'
#   homepage = 'Website of original author'
#   repo = 'https://github.com/owner/repo'
